// Generated by LiveScript 1.4.0
(function(){
  var fs, path;
  fs = require('fs');
  path = require('path');
  module.exports = function(plop){
    var getFolders, appFolders, targetApp;
    getFolders = function(srcPath){
      return fs.readdirSync(srcPath).filter(function(file){
        return fs.statSync(path.join(srcPath, file)).isDirectory();
      });
    };
    appFolders = function(){
      return getFolders('./app');
    };
    targetApp = function(){
      return {
        type: 'list',
        name: 'app',
        message: 'Choose target app',
        choices: appFolders(),
        'default': 2
      };
    };
    plop.setGenerator('component', {
      description: 'AngularLS component',
      prompts: [
        targetApp(), {
          type: 'input',
          name: 'name',
          message: 'Name of component?',
          validate: function(value){
            if (/.+/.test(value)) {
              return true;
            } else {
              return 'name is required';
            }
          }
        }
      ],
      actions: [
        {
          type: 'add',
          path: 'app/{{ dashCase app }}/components/{{ dashCase name }}/{{ dashCase name }}.spec.ls',
          templateFile: './_plop/comp.spec.txt'
        }, {
          type: 'add',
          path: 'app/{{ dashCase app }}/components/{{ dashCase name }}/{{ dashCase name }}.ls',
          templateFile: './_plop/comp.file.txt'
        }
      ]
    });
    plop.setGenerator('directive', {
      description: 'AngularLS Directive',
      prompts: [targetApp()],
      actions: []
    });
    plop.setGenerator('route', {
      description: "UI-Router Route",
      prompts: [
        targetApp(), {
          type: 'input',
          name: 'route',
          message: 'State name'
        }, {
          type: 'input',
          name: 'url',
          message: 'URL for the state'
        }, {
          type: 'input',
          name: 'controller',
          message: 'Name of the controller?'
        }
      ],
      actions: [
        {
          type: 'add',
          path: 'app/{{ dashCase app }}/routes/{{ dashCase route }}/{{ dashCase route}}.spec.ls',
          templateFile: './_plop/route.spec.txt'
        }, {
          type: 'add',
          path: 'app/{{ dashCase app }}/routes/{{ dashCase route }}/{{ dashCase route}}.ls',
          templateFile: './_plop/route.txt'
        }, {
          type: 'add',
          path: 'app/{{ dashCase app }}/routes/{{ dashCase route }}/{{ dashCase route}}.jade',
          templateFile: './_plop/route.tpl.txt'
        }
      ]
    });
  };
}).call(this);
